#!/usr/bin/env bash
# A Bash script that displays the time for 12 hours and 59 minutes:
#
# - display hours from 0 to 12
# - display minutes from 1 to 59
x=0
y=1

while [[ $x -le 12 ]]; do
	echo "Hour: $x"
	y=0

	while [[ $y -le 59 ]]; do
		echo "$y"
		((y++))
	done

	((++x))
done
